[arch]
packages = [
  # Python
  "uv",

  # C++
  "gcc",
  "gdb",
  # "codelldb",
  "lldb",
  "valgrind",
  "clang",
  "cmake",
  
  # Dotnet
  # "dotnet-sdk",

  # Node js
  "mise",

  # Docker
  "docker",
  "docker-compose",
  
  #LaTex
  "texlive-basic",
  "texlive-latexextra",
  "texlive-fontsextra",
  # "texlive-science",
  "ffmpeg",
  "python-pip"
]

[mise]
packages = [{name = "node", options = { version = "lts" }}]

# [npm]
# packages = [
#   "yarn",f
# ]